name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Test
      run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
      - name: Build
        run: |
          # linux
          GOOS=linux GOARCH=amd64 go build -o bt ./cmd/bt/main.go
          tar -czvf bt-linux-amd64.tar.gz bt && rm bt

          GOOS=linux GOARCH=arm64 go build -o bt ./cmd/bt/main.go
          tar -czvf bt-linux-arm64.tar.gz bt && rm bt

          # darwin
          GOOS=darwin GOARCH=amd64 go build -o bt ./cmd/bt/main.go
          tar -czvf bt-darwin-amd64.tar.gz bt && rm bt

          GOOS=darwin GOARCH=arm64 go build -o bt ./cmd/bt/main.go
          tar -czvf bt-darwin-arm64.tar.gz bt && rm bt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            bt-linux-amd64.tar.gz
            bt-linux-arm64.tar.gz
            bt-darwin-amd64.tar.gz
            bt-darwin-arm64.tar.gz
